app/.eslintrc.js, app/.prettierrc, app/app.js, app/bin/www, app/package-lock.json, app/package.json, app/public/index.html, app/public/stylesheets/style.css, app/routes/index.js, app/routes/users.js
=> 설정 : eslint, prettier, express 설정 완료

client/.eslintrc.js, client/.prettierrc, client/babel.config.js, client/package-lock.json, client/package.json, client/src/index.html, client/src/root.js, client/webpack.config.js, server/.eslintrc.js, server/.prettierrc, server/app.js, server/bin/www, server/package-lock.json, server/package.json, server/public/index.html, server/public/stylesheets/style.css, server/routes/index.js, server/routes/users.js
closes #1 
closes #2 
closes #3
=> 설정 : eslint, prettier, 프론트 보일러플레이트, 백엔드 보일러 플레이트, 웹팩 설정 추가

.gitignore, client/package-lock.json, client/package.json, client/src/index.html, client/src/root.js, client/src/services/utils.js, client/src/views/components/icon/index.js, client/src/views/components/mainHeader/index.js, client/src/views/pages/error404.js, client/src/views/pages/login.js, client/src/views/pages/main.js, client/src/views/styles/pages/common.css, client/webpack.config.js
=> 추가 : 웹팩 설정 및 spa 구조 잡기

client/package-lock.json, client/package.json, client/src/views/components/FAB/FAB.js, client/src/views/components/categoryListItem/categoryListItem.css, client/src/views/components/categoryListItem/categoryListItem.js, client/src/views/components/icon/icon.js, client/src/views/components/mainHeader/mainHeader.js, client/src/views/pages/main/main.js, client/src/views/styles/pages/common.css, client/webpack.config.js
=> fix : css-modules 설정

client/src/views/components/categoryListItem/categoryListItem.css, client/src/views/components/categoryListItem/categoryListItem.js, client/src/views/components/imgBox/imgBox.css, client/src/views/components/imgBox/imgBox.js, client/src/views/components/imgBox/index.js
closes #57 
이미지 박스 컴포넌트 구현했습니다.
현재 large를 제외한 나머지 클래스의 넓이와 높이는 일단 디자인 시안대로 구현하였습니다.
나중에 저희 화면에서 작게 느껴진다면 그때 바꾸면 좋을 것 같습니다.
large는 원래 CategoryListItem에 있던 크기 그대로 가져와서 사용하였습니다.
=> 추가 : 이미지 박스 컴포넌트 구현

client/src/views/components/menuHeader/index.js, client/src/views/components/menuHeader/menuHeader.css, client/src/views/components/menuHeader/menuHeader.js, client/src/views/pages/category/category.js
white, off-white, invisible 컴포넌트화 했습니다.
파라미터 color값에서 위의 이름 중 하나를 그대로 쓰시면 컴포넌트 적용 가능합니다.
예시 사진 첨부합니다.
closes #64
=> 추가 : 카테고리 아이템 white, off-white, invisible 하나로 묶어서 컴포넌트화

client/src/views/components/button/FAB.js, client/src/views/components/button/category.js, client/src/views/components/button/large.js, client/src/views/components/button/location.js, client/src/views/components/button/medium.js, client/src/views/components/button/status.js, client/src/views/components/button/tap.js, client/src/views/components/categoryListItem/categoryListItem.css, client/src/views/components/categoryListItem/categoryListItem.js, client/src/views/components/icon/icon.js, client/src/views/components/imgBox/imgBox.css, client/src/views/components/imgBox/imgBox.js, client/src/views/components/mainHeader/mainHeader.css, client/src/views/components/mainHeader/mainHeader.js, client/src/views/components/menuHeader/menuHeader.css, client/src/views/components/menuHeader/menuHeader.js, client/src/views/components/modal/dropdown.js, client/src/views/components/modal/dropdownElement.js, client/src/views/components/productListItem/productListItem.css, client/src/views/components/productListItem/productListItem.js, client/src/views/pages/category/category.js, client/src/views/pages/main/main.css, client/src/views/pages/main/main.js, client/src/views/styles/pages/common.css, client/webpack.config.js
closes #108 
모듈화 제거 후 .component .classname 형식으로 사용하기로 해요~
안 쓴 부분이나 사용안된 부분 있는지 확인 부탁드립니다.
=> hotfix : css 모듈화 빼기

client/src/services/changeActiveImgNav.js, client/src/views/components/imgNav/imgNav.css, client/src/views/components/imgNav/imgNav.js, client/src/views/components/imgNav/index.js, client/src/views/components/imgNavigation/imgNavigation.css, client/src/views/components/imgNavigation/imgNavigation.js, client/src/views/components/imgNavigation/index.js, client/src/views/pages/category/category.js
두 컴포넌트 추가 했습니다.
추가로 imgNavigation에서 버튼 active를 바꾸는 함수도 구현했습니다.
컴포넌트와 관련된 함수들을 폴더구조를 어떻게 가져가면 좋을지 고민입니다..
일단은, service 폴더에 넣긴하는데 이렇게되면 service폴더 가독성이 엄청 떨어질 것 같네요..
좋은 의견 있으시면 제안 부탁드립니다. 감사합니다 :)
closes #58 
closes #66
=> 추가 : imgNav, imgNavigation 컴포넌트 추가

client/src/views/components/chatBubble/chatBubble.css, client/src/views/components/chatBubble/chatBubble.js, client/src/views/components/chatBubble/index.js
=> 추가 : chatBubble 컴포넌트

client/src/views/components/chatBadge/chatBadge.js, client/src/views/components/imgNav/imgNav.js, client/src/views/components/imgNavigation/imgNavigation.js
클래스로 extends 했으면 이런실수를 줄일 수 있었을려나요.. 어쨋든 실수해서 죄송합니당..
closes #115
=> 리펙토링 : after_render -> afterRender

client/src/views/components/button/status.css, client/src/views/components/imgBox/imgBox.css, client/src/views/components/infoProduct/index.js, client/src/views/components/infoProduct/infoProduct.css, client/src/views/components/infoProduct/infoProduct.js
infoProduct 컴포넌트를 추가하였고 추가 도중에 이미지 small 크기가 너무 작은 것 같아 조정하였고, 마찬가지로 status버튼 크기와 아이콘 크기 또한 조절하였습니다. 결과 컴포넌트는 다음과 같습니다.
근데 이거 infoProduct 버튼을 status버튼으로 하는게 맞는지 모르겠습니다. 저거에 해당하는 버튼이 기획서 상으로는 없더군요..ㅋㅋ  어떤 버튼을 사용하는게 맞는다고 생각하시나요? 아니면 새로 버튼을 만들어야할까요..?
closes #70
=> 추가 : infoProduct 컴포넌트

client/src/views/components/modal/alert.css, client/src/views/components/modal/alert.js, client/src/views/components/modal/index.js
나중에 string은 따로 관리해야 할 것 같아 이번 작업부터는 스트링을 따로 빼놓을 생각입니다.
=> 추가 : alert 모달

client/src/images/send-green.svg, client/src/images/send.svg, client/src/services/changeSendIcon.js, client/src/views/components/chatBar/chatBar.css, client/src/views/components/chatBar/chatBar.js, client/src/views/components/chatBar/index.js, client/src/views/components/textInput/index.js, client/src/views/components/textInput/large.css, client/src/views/components/textInput/large.js, client/src/views/components/textInput/medium.css, client/src/views/components/textInput/medium.js
closes #73 
아이콘을 변경하는 함수를 어떻게 짜도 뭔가 지저분한 느낌이 들어서 뭔가 아쉽습니다
좋은 방법이 없을지..
=> 추가 : chatbar 컴포넌트

client/src/views/components/textInput/index.js, client/src/views/components/textInput/large.css, client/src/views/components/textInput/large.js, client/src/views/components/textInput/medium.css, client/src/views/components/textInput/medium.js
=> 추가 : Input 컴포넌트

client/src/images/close.svg, client/src/images/image.svg, client/src/views/components/imgButton/add/addImgButton.css, client/src/views/components/imgButton/add/addImgButton.js, client/src/views/components/imgButton/add/index.js, client/src/views/components/imgButton/delete/deleteImgButton.css, client/src/views/components/imgButton/delete/deleteImgButton.js, client/src/views/components/imgButton/delete/index.js
아직 이벤트리스너는 달지 않았는데 페이지 구현이랑 같이 하는게 나을 것 같아서 컴포넌트 만든 것으로 pr올립니다.
closes #62
=> 추가 : imgButton 

client/src/images/map-pin-black.svg, client/src/root.js, client/src/services/fitScroll.js, client/src/views/components/button/category.css, client/src/views/components/locationBar/index.js, client/src/views/components/locationBar/locationBar.css, client/src/views/components/locationBar/locationBar.js, client/src/views/pages/main/main.js, client/src/views/pages/write/index.js, client/src/views/pages/write/write.css, client/src/views/pages/write/write.js
글쓰기 페이지 레이아웃 구조 잡았습니다.
추가로 locationBar 컴포넌트를 생성하였습니다.
closes #9 
closes #30 
closes #68
=> 추가 : 글쓰기 페이지 레이아웃 및 locationBar

client/src/views/components/productBar/index.js, client/src/views/components/productBar/productBar.css, client/src/views/components/productBar/productBar.js
=> 추가 : productBar 컴포넌트

client/src/views/components/infoSaler/index.js, client/src/views/components/infoSaler/infoSaler.css, client/src/views/components/infoSaler/infoSaler.js
=> 추가 : infoSaler 컴포넌트

client/src/views/components/button/location.css, client/src/views/components/modal/alert.css, client/src/views/components/modal/dropdown.css, client/src/views/components/modal/dropdownElement.css
closes #126
이전에 지적받았던 사항입니다. on save시 자동 포맷팅 설정이 꺼져있어서 생겼던 문제로 보입니다.
=> chore : prettier 미적용 파일들 적용

client/src/root.js, client/src/views/pages/chatList/chatListPage.js, client/src/views/pages/chatList/index.js
채팅 리스트 페이지 구현 완료 하였습니다.
closes #11
=> 추가 : chatListPage 페이지 구현

client/src/root.js, client/src/views/pages/category/category.css, client/src/views/pages/menu/menu.css
closes #133 
주석을 왠만하면 안 달려고 했는데, 아예 없으면 좀 답답할 수 있겠다 싶어 간단하게만 적어놓았습니다.
=> 변경 : 슬라이딩 애니메이션의 변경

client/src/services/handleImgFiles.js, client/src/services/horizontalScroll.js, client/src/services/toggleCategory.js, client/src/views/components/button/category.css, client/src/views/components/imgButton/add/addImgButton.css, client/src/views/components/imgButton/add/addImgButton.js, client/src/views/components/imgButton/delete/deleteImgButton.js, client/src/views/pages/write/write.css, client/src/views/pages/write/write.js
위에 해당하는 기능 구현 추가하였습니다. 사진 추가 삭제기능은 아까 크롱님이 말씀해주셨던 것 처럼 하는게 좋아보이는데 후에 바뀔 여지가 있긴 하겠지만 일단 프론트 상의 구현으로 참고용으로 pr하도록 하겠습니다.
아 그리고 점점 for of 사용이 많아지는 것 같은데 쓰는 것으로 결정하고 린트 에러를 eslintrc에 빼놓는 것은 어떨까요? 가독성이 많이 안좋아지는 것 같습니다 ㅋㅋ
참고 url:
- [클릭인지 드래그인지 구분 방법](https://stackoverflow.com/questions/6042202/how-to-distinguish-mouse-click-and-drag)
- [가로 스크롤 예제](https://codepen.io/thenutz/pen/VwYeYEE)
- [input-type파일](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input/file#attr-files)
- [올린 파일 url가져오는 방법](https://developer.mozilla.org/ko/docs/Web/API/File/Using_files_from_web_applications)
closes #33 
closes #34
=> 추가 : 사진 추가 삭제 기능, 스크롤 기능 구현, 카테고리 토글 기능 구현

client/src/images/log-out.svg, client/src/root.js, client/src/views/pages/chatDetail/chatDetail.css, client/src/views/pages/chatDetail/chatDetail.js, client/src/views/pages/chatDetail/index.js
간단하게 목업데이터를 가지고 추가해놓았습니다.
메시지가 길어질때를 대비하거나 채팅창과의 인터렉션이 필요할 것 같은데 이 화면을 구현할지 아직 미지수일 것 같아서 나중에 채팅 구현할때 같이 해도 좋겠다는 판단하에 레이아웃만 구현하고 pr 합니다.
closes #12
=> 추가 : 채팅 상세페이지

client/src/root.js, client/src/views/components/button/button.css, client/src/views/components/mainHeader/mainHeader.js, client/src/views/pages/login/login.css, client/src/views/pages/login/login.js, client/src/views/pages/myinfo/index.js, client/src/views/pages/myinfo/myinfo.css, client/src/views/pages/myinfo/myinfo.js, client/src/views/pages/signup/index.js, client/src/views/pages/signup/signup.css, client/src/views/pages/signup/signup.js
closes #5
closes #6 
closes #14 
closes #20 
closes #22
=> 추가 : 로그인 페이지, 회원가입 페이지, 내 계정 페이지

client/src/images/check-mint.svg, client/src/images/check.svg, client/src/services/essentialInfoCheck.js, client/src/views/pages/write/write.css, client/src/views/pages/write/write.js
closes #31 
closes #32 
essentialInfoCheck 함수 최대한 함수로 나눠봤는데 짜놓고 보니 스파게티 코드 같네요.. ㅠㅠ
=> 추가 : 글쓰기 페이지 필수 항목 체크

client/src/services/changeDropdownDisplay.js, client/src/views/components/mainHeader/mainHeader.css, client/src/views/components/mainHeader/mainHeader.js, client/src/views/components/modal/dropdown.css, client/src/views/components/modal/dropdown.js, client/src/views/components/modal/dropdownElement.css, client/src/views/pages/main/main.js
=> 추가 : 내 동네 모달

client/src/images/chevron-left-white.svg, client/src/images/more-vertical-white.svg, client/src/root.js, client/src/views/components/imgBox/imgBox.css, client/src/views/components/menuHeader/menuHeader.css, client/src/views/pages/productDetail/productDetail.css, client/src/views/pages/productDetail/productDetail.js
closes #10 
사진 넘기기를 제외한 나머지 레이아웃을 구현하였습니다.
판매자 시점
구매자 시점
=> 추가 : 제품 상세 페이지

client/src/services/checkSignup.js, client/src/views/pages/signup/signup.js, server/controller/signup.js, server/controllers/signup.js, server/db/index.js, server/middlewares/checkSignup.js, server/routes/signup.js
=> 추가 : 백엔드 회원가입 처리

client/src/apis/index.js, client/src/views/components/mainHeader/mainHeader.js, client/src/views/pages/login/login.js, client/src/views/pages/myinfo/myinfo.js, client/src/views/pages/signup/signup.js, server/app.js, server/controllers/login.js, server/controllers/signup.js, server/package.json, server/routes/login.js
closes #21 
closes #24 
closes #76 
closes #147
=> 추가 : (프론트, 백) 로그인, 로그아웃 처리

client/src/apis/index.js, client/src/services/essentialInfoCheck.js, client/src/services/handleImgFiles.js, client/src/views/components/imgButton/delete/deleteImgButton.css, client/src/views/components/imgButton/delete/deleteImgButton.js, client/src/views/components/locationBar/locationBar.js, client/src/views/pages/signup/signup.js, client/src/views/pages/write/write.css, client/src/views/pages/write/write.js, server/app.js, server/controllers/product.js, server/controllers/signup.js, server/controllers/upload.js, server/middlewares/awsUpload.js, server/package-lock.json, server/package.json, server/routes/product.js, server/routes/upload.js
closes #151 
closes #81 
closes #150
=> 추가 : 회원가입, 로그인, 글쓰기 기능 구현

client/.eslintrc.js, client/src/services/handleImgFiles.js, client/src/views/components/imgNavigation/imgNavigation.js, client/src/views/components/menuTab/chatList/chatList.js, client/src/views/components/menuTab/likeList/likeList.js, client/src/views/components/menuTab/sellList/sellList.js, client/src/views/components/modal/dropdown.js, client/src/views/components/tabBar/tabBar.js, client/src/views/pages/category/category.js, client/src/views/pages/write/write.js, server/.eslintrc.js, server/controllers/product.js
Co-Authored-By: CurlyBat <82671736+CurlyBat@users.noreply.github.com>
=> 리펙토링 : for of 관련 eslint 규칙 off

client/src/apis/index.js, client/src/services/common/toggleHeartIcon.js, client/src/services/common/utils.js, client/src/services/main/getProduct.js, client/src/views/components/icon/icon.css, client/src/views/components/imgBox/imgBox.js, client/src/views/components/mainHeader/mainHeader.js, client/src/views/components/productListItem/productListItem.js, client/src/views/pages/main/main.js, server/product/product.controller.js, server/product/product.service.js
Co-Authored-By: CurlyBat <82671736+CurlyBat@users.noreply.github.com>
closes #50
=> 추가 : 메인페이지 관련 동작들 ( 품목 받아오기, 품목 렌더링 관련 함수들(하트변경,시간변경), 품목 받아오는 api 추가) 

client/package-lock.json, client/package.json, client/webpack.config.js
Co-Authored-By: CurlyBat <82671736+CurlyBat@users.noreply.github.com>
closes #167
=> 추가 : clean-webpack-plugin

client/src/root.js, client/src/services/common/utils.js, client/src/services/main/getProduct.js, client/src/views/components/categoryListItem/categoryListItem.css, client/src/views/pages/category/category.js, server/product/product.controller.js, server/product/product.service.js
closes #160 
이전에 쓰던 url 파싱이 아이디 동사 기준으로 파싱이 되고 있어서 쿼리를 따로 파싱해주도록 바꾸었습니다.
후에 productDetail/1 이런 방식의 url 도 추가로 파싱해줄 수 있도록 추가해야할 것 같습니다.
또한 백엔드에서 한글로 쿼리를 줄시에 decode를 해주는 작업을 깜박하고 있다가 왜 안되지 많이 애를 먹었네요.. ㅋㅋㅋ 한번 기능 잘 돌아가는지 확인 부탁드리겠습니다!
=> 추가 : 카테고리 페이지에서 카테고리 클릭시 메인 페이지에 관련 상품 렌더링

client/src/root.js, client/src/services/main/getTown.js, client/src/services/town/getTowns.js, client/src/views/components/mainHeader/mainHeader.js, client/src/views/components/modal/dropdown.js, client/src/views/pages/productDetail/index.js, client/src/views/pages/town/index.js, client/src/views/pages/town/town.css, client/src/views/pages/town/town.js, server/app.js, server/signup/signup.controller.js, server/signup/signup.middleware.check.js, server/signup/signup.service.js, server/town/town.controller.js, server/town/town.service.js
closes #13 
현재 town1을 기본 값으로 헤더에 보여주게 설정되어있습니다.
이제 모달창을 띄워서 백엔드와 통신한다면 동네 설정은 끝입니다
=> 추가 :  동네 정보 가져오기, 동네 설정 페이지

client/src/services/common/imageSlider.js, client/src/services/common/productOnClick.js, client/src/services/common/toggleHeartIcon.js, client/src/services/common/utils.js, client/src/services/main/getProduct.js, client/src/views/components/imgBox/imgBox.css, client/src/views/components/imgBox/imgBox.js, client/src/views/components/imgNav/imgNav.css, client/src/views/components/imgNavigation/imgNavigation.js, client/src/views/components/productBar/productBar.js, client/src/views/components/productListItem/productListItem.js, client/src/views/pages/productDetail/productDetail.css, client/src/views/pages/productDetail/productDetail.js, server/product/product.controller.js, server/product/product.service.js
일단 기본 기능만 해두었고 보완 할 점 계속 보완해나가겠습니다.
=> 추가 : 상품 상세 페이지 기본 기능

client/src/apis/index.js, client/src/services/common/utils.js, client/src/services/town/addAlert.js, client/src/services/town/addInputPopup.js, client/src/services/town/deleteTown.js, client/src/services/town/getTowns.js, client/src/services/town/putTown.js, client/src/views/components/button/location.js, client/src/views/components/modal/alert.css, client/src/views/components/modal/alert.js, client/src/views/components/modal/inputPopup.css, client/src/views/components/modal/inputPopup.js, client/src/views/pages/town/town.css, server/town/town.controller.js, server/town/town.service.js
closes #165 
동네 설정 페이지에서 모달을 띄워주고,
추가 및 삭제를 구현하였습니다.
=> 추가 : 동네 설정 페이지의 기능 구현

client/src/services/main/changeDropdownDisplay.js, client/src/views/components/modal/dropdown.js, server/product/product.service.js
=> 추가 : 모달에 있는 동네 클릭 시 해당 동네 물건 받아오기

server/app.js, server/ecosystem.config.js, server/package-lock.json, server/package.json
pm2 배포 도중 [에러](https://stackoverflow.com/questions/44882535/warning-connect-session-memorystore-is-not-designed-for-a-production-environm)가 나서 해결방법을 찾아서 cookie session으로 교체했습니다.
=> 세팅 : pm2 환경설정 및 express-session cookie-session으로 교체

client/package-lock.json, client/package.json, client/src/apis/index.js, client/src/views/pages/signup/signup.js, client/webpack.config.js
defineplugin이용해서 api url 구분 하였습니다.
=> chore : dotenv 와 defineplugin이용 배포와 dev api url 구분

client/src/views/components/commingSoonModal/commingSoonModal.css, client/src/views/components/commingSoonModal/commingSoonModal.js, client/src/views/components/commingSoonModal/index.js, client/src/views/components/menuTab/chatList/chatList.js, client/src/views/components/productBar/productBar.js, client/src/views/pages/chatDetail/chatDetail.js, client/src/views/pages/chatList/chatListPage.js, client/src/views/pages/productDetail/productDetail.js, client/webpack.config.js
구현 못한 건 아쉽지만 ux 적인 관점에서 모달을 만들어 사용자 경험을 조금 낫게 해보려고 시도했습니다..!
closes #181
=> 추가 : 데브 api url 변경 및 comming soon modal 추가

client/src/index.html, client/src/services/write/essentialInfoCheck.js, client/src/services/write/getTown.js, client/src/views/components/locationBar/locationBar.css, client/src/views/components/locationBar/locationBar.js, client/src/views/pages/write/write.js
=>  추가 : 글쓰기 페이지에서 동네 정보 선택

client/src/views/components/menuTab/sellList/sellList.js, client/src/views/components/modal/productDropdown.css, client/src/views/components/modal/productDropdown.js, client/src/views/pages/menu/menu.css, client/src/views/pages/productDetail/productDetail.js
흑흑 하루전에 짜는 코드는 정말 더럽네요.. 아닌가.. 프레임워크를 잘 못짜서인가 ㅠㅠㅠ 아쉽습니다..!
closes #183
=> 추가 : 상품 상세페이지, 판매목록 케밥 버튼 클릭시 모달 추가

server/db/index.js
=> 추가 : 백엔드 서버 시작 시 테이블 생성

client/src/views/components/productBar/productBar.js, client/src/views/components/productListItem/productListItem.js
=> hotfix : 가격 쉼표와 원 표시

client/src/apis/index.js, client/src/views/components/menuTab/sellList/sellList.js, client/src/views/components/modal/alert.js, client/src/views/components/modal/productDropdown.js, client/src/views/pages/productDetail/productDetail.js, server/product/product.controller.js, server/product/product.service.js
=> 추가 : 프로덕트 삭제 기능
